### ISSUE TITLE
Documentation not working and stream confirmation

### ISSUE THREAD

**Issue by AbdulWMughal** [c410-f3r/wtx#190]
Hi, two points:

1) documentation doesn't seem to be loading i keep getting ‘404 file not found’

2) Does WTX Postgres database client fully support async transactions and streaming of queries both via client’s api’s?

Does the client have all the features that tokio_posgres, sqlx have?

Could you modify the below code to show me transaction (commit, rollback ideally) and streaming (queries streaming) being used? So we can make a decision based on the above needs.

Thanks

`

use wtx::prelude::*;
 use std::error::Error;

 #[tokio::main]
 async fn main() -> Result<(), Box<dyn  Error>> {

    let db_url =  "……";

    let pool = wtx::ClientPool::new(db_url, 5)?;

    let client = pool.get()?;

    let stmt = client.prepare_typed("SELECT  id, name FROM users", &[]).await?;
    let stream = client.stream(stmt, &[])?;

    while let Some(row) =  stream.try_next().await? {
        let id: i32 = row.get("id");
        let name: String = row.get("name");

        println!("User id: {}, name: {}", id,  name);
    }
  Ok(())
 } 

`

**Comment by c410-f3r** [comment]
Hello,

> documentation doesn't seem to be loading i keep getting ‘404 file not found’

Thanks, I will take a look.

> Does WTX Postgres database client fully support async transactions and streaming of queries both via client’s api’s?

`wtx` does not support streaming at the current time and has poor transaction support.

> Does the client have all the features that tokio_posgres, sqlx have?

Probably not. Features are added when the need arises.

Here goes your modified code. Another example using TLS and transaction is available at https://github.com/c410-f3r/wtx/blob/main/wtx/examples/database-client-postgres-tokio-rustls.rs.

```rust
use tokio::net::TcpStream;
use wtx::{
  database::{
    client::postgres::{Config, Executor, ExecutorBuffer},
    Executor as _, Record, Records,
  },
  misc::UriRef,
  rng::StdRng,
};

#[tokio::main]
async fn main() -> wtx::Result<()> {
  let uri_ref = UriRef::new("...");
  let mut rng = StdRng::default();
  let mut exec = Executor::connect(
    &Config::from_uri(&uri_ref)?,
    ExecutorBuffer::with_default_params(&mut rng)?,
    &mut rng,
    TcpStream::connect(uri_ref.host()).await?,
  )
  .await?;
  let records = exec
    .fetch_many_with_stmt("SELECT id, name FROM users", (), |_| Ok::<_, wtx::Error>(()))
    .await?;
  for record in records.iter() {
    println!("{}", record.decode::<_, u32>("id")?);
    println!("{}", record.decode::<_, &str>("name")?);
  }
  Ok(())
}
```

You probably shouldn't use this library. `SQLx` and `tokio_posgres` are much more mature and reliable projects.

**Comment by AbdulWMughal** [comment]
If you still have the codes used for this benchmark could please provide the files (tokio_posgres, diesel-async, sqlx) in your response.

![IMG_3484](https://github.com/user-attachments/assets/432dabdc-5c51-44db-b052-b962e9f5b613)

WTX currently has built in database connection pooling and the database client. Initial benchmarks show wtx to beat all other crates. 

https://github.com/diesel-rs/metrics/

However i believe the next steps are definitely to add full native support for transactions (incl. commit/rollback) and streaming to WTX. For streaming tokio_posgres has ‘raw’ versions of its macros like query_raw instead of query. Which implicitly provides full streaming capability with a simple addition of ‘_raw’. You could so something similar. Your approach to maximising consistent performance resonates. WTX is already beating everyone else in initial benchmarks. I believe the addition of the above (native transactions and streaming) and further improvements to making it easier to use while reducing boiler plate code without sacrificing its current performance will warrant widespread adoption of this crate.

I will keep a steady eye on this project and hope it will be ready in the near future for us to switch to in production. So far the benchmarks have us all impressed.

Kind Regards
Abdul

**Comment by c410-f3r** [comment]
> If you still have the codes used for this benchmark could please provide the files (tokio_posgres, diesel-async, sqlx) in your response.

This is an old benchmark removed in favor of https://github.com/diesel-rs/metrics. The code is still available in the git history if you want to take a look (https://github.com/c410-f3r/wtx/commit/55857e144d5dc3de1d45da94225b05c47f2c218e#diff-0caf9cba34e6c9578e3eb5b353cff8631c9515a7e4144ed7cd0922617c391be0).

> However i believe the next steps are definitely to add full native support for transactions (incl. commit/rollback) and streaming to WTX. For streaming tokio_posgres has ‘raw’ versions of its macros like query_raw instead of query. Which implicitly provides full streaming capability with a simple addition of ‘_raw’. You could so something similar. Your approach to maximising consistent performance resonates. WTX is already beating everyone else in initial benchmarks. I believe the addition of the above (native transactions and streaming) and further improvements to making it easier to use while reducing boiler plate code without sacrificing its current performance will warrant widespread adoption of this crate.

> I will keep a steady eye on this project and hope it will be ready in the near future for us to switch to in production. So far the benchmarks have us all impressed.

Thank you. I plan to add more features in the future and will also research ways to further improve performance.

In the meanwhile, please continue using more reliable projects like `diesel`, `sqlx` or `tokio-postgres` in production environments.

**Comment by c410-f3r** [comment]
https://c410-f3r.github.io/wtx/database/client-connection.html

The documentation of the client has been updated with a more intuitive example so I am going to close this issue.
