### ISSUE TITLE
Receiving Unexpected EOF error on tls handshake

### ISSUE THREAD

**Issue by mhart626** [c410-f3r/wtx#288]
Hi, I'm trying to subscribe to the following endpoint on a ws subscription:
wss://fstream.binance.com/ws/depth10

I seem to receive a UnexpectedEof error on the tls handshake:
IoError(Custom { kind: UnexpectedEof, error: "tls handshake eof" })

To replicate the error, you can use the above uri, and send a json payload:
json!({
     "method": "SUBSCRIBE",
     "params": "btcusdt@depth10@100ms",
     "id": 1,
})

Note: if you are trying to subscribe from the US, you may need a VPN (they will send a 404 I believe when trying to connect otherwise).

**Comment by c410-f3r** [comment]
A strange behavior that never happened. Unfortunately I won't be able to take a look until the weekend.
